# This is a basic workflow to help you get started with Actions
# every step must define a `uses` or `run` key

name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-aplication-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"
  
on:
  push:
    branches: 
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git clone our repo 
        uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configuration my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
      
        with:
         aws-access-key-id       :  ${{ secrets.MY_AWS_ACCESS_KEY }}
         aws-secret-access-key   :  ${{ secrets.MY_AWS_SECRET_KEY }}
         aws-region              :  ${{ env.AWS_REGION_NAME }}
          
      - name: Copy Deployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/    
          
      - name: Print Happy Message for CI finish        
        run: echo "CI Pipeline part Finished successfully!"
